### PR TITLE
CurveBoost: StakeDAO Liquid Lockers strategies for boosted CRV Rewards

### PR DESCRIPTION
**Pull request by kobe-eth**
To benefit from the maximum rewards, here is a compatible strategy to migrate from your Curve Gauges strategies to https://lockers.stakedao.org/.

Stake Dao Lockers provide a multichain boost using its increasing balance of 23M veCRV and is the first protocol to give a multichain boost on Curve. 

PR contains: 
`contracts/BIFI/strategies/StakeDAO/StrategyLLCurveLP.sol` -> fork of your current StrategyCurveLP but using StakeDAO Locker's architecture instead

`forge/test/StakeDAO/StrategyLLCurveLPTest.t.sol` -> Basic Test forked from your base test file using Foundry.

@sirbeefalot @cartman-dev

### CODE REVIEW

**Review by roman-monk — CHANGES_REQUESTED** [review]
cool!
could you add forge-std as node_module with specific commit instead submodule please?

**Comment by kobe-eth** [comment]
> cool! could you add forge-std as node_module with specific commit instead submodule please?

Forge-std using submodules, couldn't figure out how to add it on node_modules since `yarn` doesn't download the submodules recursively, so I flattened the contract and updated the test.sol you already had that was an old version of it.

**Comment by kobe-eth** [comment]
I've also added a claim through StakeDAO Lockers so rewards flow constantly using the harvest() function of the strategy, for better returns.

**Comment by roman-monk** [comment]
> Let me know if you need anything 🔥

just `pragma solidity ^0.8.0` to not break yarn compile and pass check.

this is how forge-std included in optimism
https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/package.json#L70
https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/foundry.toml#L12

**Comment by roman-monk** [comment]
thanks!

**Pull request merged**
